Repository openshift/service-catalog, pull requests merged in 2018-08, with the labels that each got.

#18 Tooling addition and go version bump
  UPSTREAM-MERGE.sh
  hack/lib/constants.sh
Labels: approved, lgtm, size/L

#21 V0.1.30 rebase master
  Gopkg.lock
  Gopkg.toml
  UPSTREAM-VERSION
  charts/catalog/Chart.yaml
  charts/catalog/README.md
  charts/catalog/templates/apiserver-deployment.yaml
  charts/catalog/templates/controller-manager-deployment.yaml
  charts/catalog/values.yaml
  cmd/svcat/broker/register_cmd.go
  cmd/svcat/broker/register_cmd_test.go
  cmd/svcat/testdata/output/completion-bash.txt
  cmd/svcat/testdata/output/completion-zsh.txt
  cmd/svcat/testdata/plugin.yaml
  docs/devguide.md
  docs/feature-gates.md
  docs/install.md
  docsite/_data/devguide.yaml
  pkg/controller/controller_binding.go
  pkg/controller/controller_binding_ns_test.go
  pkg/controller/controller_binding_test.go
  pkg/controller/controller_instance.go
  pkg/controller/controller_instance_test.go
  pkg/features/features.go
  pkg/registry/servicecatalog/binding/storage.go
  pkg/registry/servicecatalog/binding/strategy_test.go
  pkg/registry/servicecatalog/clusterservicebroker/storage.go
  pkg/registry/servicecatalog/clusterservicebroker/strategy_test.go
  pkg/registry/servicecatalog/clusterserviceclass/storage.go
  pkg/registry/servicecatalog/clusterserviceplan/storage.go
  pkg/registry/servicecatalog/instance/storage.go
  pkg/registry/servicecatalog/instance/strategy_test.go
  pkg/registry/servicecatalog/servicebroker/storage.go
  pkg/registry/servicecatalog/servicebroker/strategy_test.go
  pkg/registry/servicecatalog/serviceclass/storage.go
  pkg/registry/servicecatalog/serviceplan/storage.go
  pkg/registry/servicecatalog/tableconvertor/tableconvertor.go
  pkg/svcat/service-catalog/assets/ca
  pkg/svcat/service-catalog/broker.go
  pkg/svcat/service-catalog/broker_test.go
  pkg/svcat/service-catalog/options.go
  pkg/svcat/service-catalog/sdk.go
  pkg/svcat/service-catalog/service-catalogfakes/fake_svcat_client.go
  test/integration/controller_instance_test.go
  test/integration/controller_test.go
  test/util/util.go
  vendor/k8s.io/apimachinery/pkg/api/meta/table/table.go
  vendor/k8s.io/apimachinery/pkg/util/duration/duration.go
Labels: approved, lgtm, size/XXL

#22 add luksa
  OWNERS
Labels: approved, lgtm, size/XS
