Repository openshift/service-catalog, pull requests merged in 2019-01, with the labels that each got.

#42 [3.10] Add readiness probes and split checks from liveness probes (#2490)
  charts/catalog/templates/apiserver-deployment.yaml
  charts/catalog/templates/controller-manager-deployment.yaml
  charts/catalog/templates/rbac.yaml
  cmd/apiserver/app/server/run_server.go
  cmd/controller-manager/app/controller_manager.go
Labels: approved, lgtm, size/L

#43 [3.11] Add readiness probes and split checks from liveness probes (#2490)
  charts/catalog/templates/apiserver-deployment.yaml
  charts/catalog/templates/controller-manager-deployment.yaml
  charts/catalog/templates/rbac.yaml
  cmd/apiserver/app/server/run_server.go
  cmd/controller-manager/app/controller_manager.go
Labels: approved, lgtm, size/M

#44 install service catalog via marketplace for e2e
  hack/create-subscription.sh
  hack/run-e2e.sh
  hack/svcat-catalogsourceconfig.yaml
  hack/svcat-operatorgroup.yaml
  hack/svcat-subscription.yaml
  manifests/04-services.yaml
Labels: approved, lgtm, size/L

#45 Service catalog is not ready to be in the release payload
  Dockerfile
  Dockerfile.rhel7
Labels: approved, lgtm, size/XS
